# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
makeup = Makeup.create([{ name: 'Glossier Boy Brow', price: 22, img_url: "https://cdn.cliqueinc.com/cache/posts/169326/reviewed-glossiers-boy-brow-1603137-1450474724.500x0c.jpg?interlace=true&quality=70", description: "The creamy wax formula is inspired by traditional hair pomade for soft, flexible hold that doesn’t stiffen or flake"},
                        { name: "Milk Makeup Lip + Cheek ", price: 24, img_url:  "https://www.milkmakeup.com/dw/image/v2/BBWR_PRD/on/demandware.static/-/Sites-master-catalog/default/dwdf5fe09d/images/large/Lip+Cheek-Perk-cap-800x1100-2.png?sw=260&sh=360&sm=fit", description: "Mango butter and Milk Melt Technology help stick blend seamlessly into skin, while also providing hydrating benefits"},
                        { name: 'RMS "UN" Cover-Up ',price: 36, img_url: "https://typeset-beta.imgix.net/uploads/image/2017/9/5/bf99e693-4a7c-45ab-ac4d-2e2e05245c13-rm4036290_rms_beauty__un_cover-up_000_13855_x1000progressive.jpg", description: "Use as a foundation or a light concealer as it visibly melts into the skin while covering imperfections and redness"},
                        { name: "Milk Makeup Kush Mascara", price: 24, img_url: "https://thenotice.net/wp-content/uploads/2018/05/milk-kush-mascara.jpg", description: "Conditioning hemp-derived cannabis oil fuses heart-shaped fibers to lashes for thickness without the fallout. The hydrating formula also fills the hollow fibers for a double dose of volume"},
                        { name: "Makeup Forever Lipstick", price: 22, img_url: "https://i.ebayimg.com/thumbs/images/g/JIMAAOSwEEBaKW~V/s-l225.jpg", description: "A collection of high-impact lipsticks in dimensional shades that have been handcrafted to deliver extreme moisture, soft texture, and creamy wear " },
                        { name: "Burt's Bees Foundation", price: 17, img_url: "https://www.burtsbees.com/dw/image/v2/AAPA_PRD/on/demandware.static/-/Sites-burtsbees-master-catalog/default/dwf8f0ceaa/images/large/NI-37172_BBd_FCE_BTL_Liquid_Honey_SideCap1_1040_21-04-17-1520.jpg?sw=225&sh=225&sm=fit&q=100", description: "Our 98.9% natural, full coverage Liquid Makeup evens and smoothes skin for a radiant, natural-looking finish"},
                        { name: "Bare Minerals Tinted Hydrating Gel Cream", price: 37, img_url: "https://29secrets.com/wp-content/uploads/2017/08/bareMinerals-Complexion-Rescue-COMP-637x850.jpg", description: "The formula is packed with skin-loving minerals, marine botanicals and antioxidants to help improve and hydrate the skin"},
                        { name: "Glossier Cloud Paint", price: 18, img_url: "http://cdn.shopify.com/s/files/1/2300/0341/products/download_095dc891-fcdf-46e3-b88f-ffd8e7e08b33_grande.jpg?v=1531824627", description: "Pillowy, gel-cream formula designed for a healthy, flushed-from-within glow"},
                        { name: "HourGlass Veil Mineral Primer", price: 54, img_url: "https://i.ebayimg.com/images/g/VukAAOSwH1VaxNBF/s-l225.jpg", description: "An oil-free primer with a silky, airy texture that leaves a smooth canvas for makeup, while reducing the look of redness, pores, and wrinkles"},
                        { name: "RMS Luminizer X Quad", price: 38, img_url: "https://i.ebayimg.com/images/g/b0QAAOSw-olaPUZB/s-l225.jpg", description: "This formula creates a sensuous, sheer, luminous glow and enhances the skin's natural youthfulness without being sticky, greasy or glittery"}
                      ])
