# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
makeup = Makeup.create([{ name: 'Glossier Boy Brow', price: 22, img_url: "https://bbblog799.files.wordpress.com/2018/04/unknown-3.jpeg?w=1000", description: "The creamy wax formula is inspired by traditional hair pomade for soft, flexible hold that doesn’t stiffen or flake"},
                        { name: 'RMS "UN" Cover-Up ',price: 36, img_url: "https://typeset-beta.imgix.net/uploads/image/2017/9/5/bf99e693-4a7c-45ab-ac4d-2e2e05245c13-rm4036290_rms_beauty__un_cover-up_000_13855_x1000progressive.jpg", description: "Use as a foundation or a light concealer as it visibly melts into the skin while covering imperfections and redness"},
                        { name: "Jane Iredale Mascara", price: 34, img_url: "https://gimmethegoodstuff.org/wp-content/uploads/Jane-Iredale-PureLash-Lengthening-Mascara-1.jpg", description: "Made with natural fibers, this advanced formula increases volume by 385%* to create fuller, more dramatic-looking lashes. The hourglass brush curls, separates, and plumps for high-drama glam–without clumping, flaking or smudging"},
                        { name: "Makeup Forever Lipstick", price: 22, img_url: "https://i.ebayimg.com/thumbs/images/g/JIMAAOSwEEBaKW~V/s-l225.jpg", description: "A collection of high-impact lipsticks in dimensional shades that have been handcrafted to deliver extreme moisture, soft texture, and creamy wear" },
                        { name: "Burt's Bees Foundation", price: 17, img_url: "https://www.burtsbees.com/dw/image/v2/AAPA_PRD/on/demandware.static/-/Sites-burtsbees-master-catalog/default/dwf8f0ceaa/images/large/NI-37172_BBd_FCE_BTL_Liquid_Honey_SideCap1_1040_21-04-17-1520.jpg?sw=225&sh=225&sm=fit&q=100", description: "Our 98.9% natural, full coverage Liquid Makeup evens and smoothes skin for a radiant, natural-looking finish"},
                        { name: "RMS Lip2Cheek", price: 37, img_url: "https://i.ebayimg.com/images/g/uN8AAOSw~oFXDaxF/s-l225.jpg", description: "A multitasking cream color for lips and cheeks. This unique formula hydrates and protects with abundant mineral color, creating a beautiful, natural finish on both lips and cheeks"},
                        { name: "Glossier Cloud Paint", price: 18, img_url: "http://cdn.shopify.com/s/files/1/2300/0341/products/download_095dc891-fcdf-46e3-b88f-ffd8e7e08b33_grande.jpg?v=1531824627", description: "Pillowy, gel-cream formula designed for a healthy, flushed-from-within glow"},
                        { name: "HourGlass Veil Mineral Primer", price: 54, img_url: "https://i.ebayimg.com/images/g/VukAAOSwH1VaxNBF/s-l225.jpg", description: "An oil-free primer with a silky, airy texture that leaves a smooth canvas for makeup, while reducing the look of redness, pores, and wrinkles"},
                        { name: "RMS Luminizer X Quad", price: 38, img_url: "https://i.ebayimg.com/images/g/b0QAAOSw-olaPUZB/s-l225.jpg", description: "This formula creates a sensuous, sheer, luminous glow and enhances the skin's natural youthfulness without being sticky, greasy or glittery"}
                      ])

review = Review.create([{ makeup_id: 1, name: 'Sylvia', city: 'Stockholm', rating: 4, content: "This is one of the BEST brow products I've ever used! I only gave it four stars because it runs out in about six weeks, which is a shame. It's tough to spend almost twenty pounds (factoring in shipping) so often for so little product."},
                        { makeup_id: 2, name: 'Mila', city: 'Houston', rating: 5, content: "I've used this for the past two years and it's incredible what it's done for my skin. I don't get acne anymore and I used to need a ton of concealer, now I don't use any more foundation under my eyes than I do anywhere else. My holy grail concealer"},
                        { makeup_id: 3, name: 'Nancy', city: 'Tampa', rating: 5, content: "I have extremely sensitive skin and eyes. This is the first mascara that I could wear all day and not feel like scratching my face or eyes out. My friends are astounded to see me wearing make up. I love it!"},
                        { makeup_id: 4, name: 'Cindy', city: 'Copenhagen', rating: 5, content: "This berry is the perfect fall shade I was looking for. It's a beautiful, deep berry color. I've worn it twice now and have had no problems with smudge or wear. I would recommend a liner and brush for the perfect berry lip."},
                        { makeup_id: 5, name: 'Rashel', city: 'San Francisco', rating: 3, content: "I Love Burts Bees but was not impressed with this foundation. The texture of it was greasy and somewhat thin. The coverage was very poor, no matter how much I put on. That being said, It wasn't terrible. I got a few good uses out of it, and the packaging was very convenient. It is also fairly natural compared to most other foundations on the market. But it was definitely not my favorite Burts Bees buy."},
                        { makeup_id: 6, name: 'Reya', city: 'Madrid', rating: 5, content: "Love this red! It's a good balance of sheer with enough color to look almost like a stain, but still very hydrating. I primarily use this on my lips but is also good for blush. The color stays on pretty well and doesn't dry out my lips."},
                        { makeup_id: 7, name: 'Courtney', city: 'Durham', rating: 5, content: "I use this for a natural, rosy-looking wash of color on the apples of my cheeks and the bridge of my nose. It is stunning! My face looks sun-kissed and flush with color. Will definitely buy again."},
                        { makeup_id: 8, name: 'Leia', city: 'Lisbon', rating: 4, content: "Feels like silk on the skin! This was my go to until my skin decided to play me and get super dry. I wouldn't recommend on dry skin."},
                        { makeup_id: 9, name: 'Alexandra', city: 'Boston', rating: 5, content: "Perfect The living luminizer is still my favourite but this palette is beautiful and I use it all the time. Don't hesitate to buy"}



  ])
